---
title: "Coverage of vpts data sources"
---

```{r pkgsetup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, echo = F,
  comment = "#>"
)
```

Various sources of VPTS coverage different coverage, meaning different radars and time periods are included. Here we visualize per radar and data source the temporal coverage. If you click on a radar on the map a plot shows the percentage of days where data has been found per month.

```{r setup, message=FALSE}
library(getRad)

require(leafpop)
require(leaflet)
require(ggplot2)
require(dplyr)
library(htmltools)
```
```{r data}

cvr <- get_vpts_coverage()
wr <- get_weather_radars("opera") |>
  group_by(radar) |>
  arrange(status) |>
  slice_tail(n = 1)
```



```{r}
cvr_summary <- cvr |>
  group_by(radar, source,
    month = factor(month.name[lubridate::month(date)],
      levels = month.name
    ), year = lubridate::year(date)
  ) |>
  summarise(n = n(), n_max = unique(lubridate::days_in_month(date)), .groups = "drop")
```

```{r create_maps}
html <- list()
for (i in unique(cvr$source)) {
  cvrsub <- cvr_summary |> dplyr::filter(source == i)
  years <- seq(min(cvrsub$year), max(cvrsub$year), 1)
  cvrsub |>
    group_by(radar) |>
    summarize(grph = list(ggplot(data = pick(everything())) +
      geom_tile(aes(x = month, y = year, fill = (n / n_max) * 100)) +
      scale_fill_viridis_c("Coverage", limits = c(0, 100), breaks = (0:5) * 20, labels = paste0((0:5) * 20, " [%]")) +
      theme_minimal() +
      scale_y_continuous("Year", breaks = years, limits = range(years) + c(-.51, .51)) +
      theme(
        axis.text.x = element_text(angle = -90, vjust = 0.5, hjust = 0),
        plot.title = element_text(hjust = 0.5),
        panel.grid = element_blank()
      ) +
      ggtitle(radar) +
      scale_x_discrete("Month", breaks = month.name, labels = month.name, limits = month.name))) -> res
  res$grph[[1]]
  suppressWarnings(res |> left_join(wr, by = join_by(radar))) -> res
  ll <- NULL
  if (any(is.na(res$longitude))) {
    ll <- p(glue::glue("One or more radars were omited from the map as no location is found in the opera archive ({glue::glue_collapse(paste0('`',res$radar[is.na(res$longitude)],'`'), ', ', last = ' and ' )})."))
    }
  res <- res |> filter(!is.na(longitude))
  lft <- leaflet() |>
    addTiles() |>
    addCircleMarkers(lng = res$longitude, lat = res$latitude, label = res$radar, 
                     popup = popupGraph(res$grph))
  html <- c(html, list(h3(i), lft, ll))
}
tagList(html)
```
